### ISSUE TITLE
Replace (horizontal) tabs with tabs of the SL design system

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1008]
```[tasklist]
### Tasks
- [x] Implement SL DS tab
- [x] Vertical navigation needs to be connected with new tab component
- [ ] https://github.com/sl-design-system/components/issues/1034
```
