### ISSUE TITLE
improve contrast of dropdown

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1010]
After reviewing SL theme color contrast needs to be improved in several components not just the dropdown.

```[tasklist]
### Themes
- [x] SL light
- [x] SL dark
```

```[tasklist]
### Tasks
- [x] update tokens of all themes
- [x] update figma components
- [ ] https://github.com/sl-design-system/components/issues/1009
- [x] change background of live example in documentation website to neutral.50 (light mode) and neutral.900 (dark mode)
```
