### ISSUE TITLE
Structured feedback collection

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1023]
```[tasklist]
### Tasks
- [ ] https://github.com/sl-design-system/components/issues/1200
- [ ] https://github.com/sl-design-system/components/issues/1261
- [x] [structure feedback collection] communicate new process with users
```
