### ISSUE TITLE
Make accordion available in all themes

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1029]
```[tasklist]
### Tasks
- [x] make sheet in figma
- [x] copy tokens to all themes
- [x] Bingel DC
- [x] Bingel INT
- [x] Clickedu
- [x] Editorial Suite
- [x] ItsLearning
- [x] Kampus
- [x] Magister light
- [x] Magister dark
- [x] Max Online
- [x] My Digital Book
- [x] My Vanin
- [x] NEON light
- [x] NEON dark
- [x] Sanoma Utbildning
- [x] TEAS
- [ ] test in storybook
```
