### ISSUE TITLE
[Contextual tokens] Final approach

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1035]
Discuss with everyone in the team during getting together.

```[tasklist]
### Tasks
- [x] Define the final structure during getting together (decide)
- [x] Discuss next steps
- [x] Discuss workflow
- [x] Roald will share approach with the team
```
