### ISSUE TITLE
[badge] Size property doesn't match actual sizes

### ISSUE THREAD

**Issue by jpzwarte** [sl-design-system/components#1042]
(this screenshot is not at 100% scale, so you can't draw any conclusions from it)
![CleanShot 2024-03-12 at 15 06 33@2x](https://github.com/sl-design-system/components/assets/3968/e2485d7d-f080-4a42-ae96-e97a781aae49)

We should adjust the sizes a badge can have to better match the actual visual size. Perhaps `2xl` -> `md` and adjust the rest accordingly?
```[tasklist]
### Tasks
- [ ] update documentation
- [x] update naming of tokens
- [ ] update badges in all themes
- [ ] update in code
- [x] sizes: 2XS XS SM MD LG XL and MD will be the default
- [x] double check badges in avatar within Figma Toolkit
- [ ] specify as minor in changeset
```
