### ISSUE TITLE
[tabs] Changes Figma component

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1055]
There are inconsistencies with the tabs component in Storybook and the Figma component.
Figma component needs to be updated.

Also see #1058 for the changes made to the web components.

```[tasklist]
### Tasks
- [ ] Discuss changes with Jeroen before starting
- [ ] Check height, is it consistent with the one we have in Storybook?
- [ ] Title without subtitle should use a regular font instead of demibold
- [ ] Title should use demibold if the subtitle is used
- [ ] Check the alignment of the more button, is it still consistent? (vertical and horizontal tabs)
- [ ] border on full width (no margin)
- [ ] scroll idicator has changed (do we support this within figma as well?) Jeroen applied a gradient? Do we want to keep this?
- [ ] outline has to be negative
- [ ] Update changes in all themes
- [ ] wheb hovering a tab with icon the icon isn't visible in prototype.
```
