### ISSUE TITLE
Improve getting started for developers

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1057]
```[tasklist]
### Tasks
- [ ] document that polyfills are needed
- [ ] make a checklist at the top of that page that devs can easily follow
- [ ] mention peer dependencies
- [ ] describe easy check to see if a web component is loaded (#shadow-root in devtools)
```
