### ISSUE TITLE
[handling hint + validation messages]update in figma (all themes) make sure designers can still use the same component

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1065]
Form controls are already in use, don't remove the current components within Figma, rather update current component or create a new one and aks designers to update the component within Figma.

Order needs to be changed in following components:

- checkbox group (Alvaro)
- Radio group (Alvaro)
- Select (Roald)
- Text area (remove error and success icon, icon is shown in validation message) (Alvaro)
- Text field (remove error and success icon, icon is shown in validation message) (Alvaro)
- Switch (vertical layout) (Alvaro)

```[tasklist]
### Tasks
- [x] Create validation message component
- [x] Make first proposal in Sanoma Learning theme (dark + light)
- [ ] Bingel DC
- [ ] Bingel INT
- [ ] Clickedu
- [ ] Editorial Suite
- [ ] ItsLearning
- [ ] Kampus
- [ ] MAgister (dark + light)
- [ ] Max Online
- [ ] My Digital Book
- [ ] Myvanin
- [ ] NEON (dark + light)
- [ ] Sanoma Utbildning
- [ ] TEAS
```
