### ISSUE TITLE
[Tree] Setup component

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1100]
A Tree View is a hierarchical UI component that displays a nested structure of items, allowing users to expand, collapse, and navigate content levels.

## Purpose
- Display and organise hierarchical data.
- Enable efficient navigation of complex structures by progressively disclosing information.
- Allow interaction (e.g., selection, actions) with nodes at any level.
- Provide a clear visual representation of parent-child relationships.

### Hierarchical Content
The Tree View is ideal for displaying and navigating hierarchical data, such as file systems, category structures, or organisational charts. It groups related data with nested relationships in a clear and organised way. It is a powerful tool for organising subject lesson content in educational applications. For example, it represents a syllabus with modules as parent nodes and lessons as child nodes, enabling students to intuitively explore and navigate their coursework. 

### Expandable Content
The Tree View allows users to dynamically expand or collapse data sections, enabling a cleaner interface focusing only on relevant information. This interactive functionality is handy when managing large amounts of content, where each item contains complex data or detailed information. It ensures users can explore deeply without being overwhelmed.

### Simple Structures
Avoid using Tree View when your data is flat, only requires one level of nested information, or if a simpler component like an accordion or data table would suffice. This includes use cases like showing a single level of expandable content, such as FAQ answers. 

### Global Navigation
Do not use Tree View as the primary navigation for your product’s UI. For global sidebar navigation, it's better to use a dedicated UI Shell left panel that suits this purpose.

### Elements Toggle
Tree View is not ideal for showing and hiding UI elements or content within a page. If the interaction only involves collapsing or expanding content at a basic level, consider using other components like accordions or dropdowns for a more straightforward solution.

<img width="960" alt="Frame 15276-1" src="https://github.com/user-attachments/assets/3dc5622c-788e-4058-a401-9b4329cf6d87" />
<img width="960" alt="Frame 15276-2" src="https://github.com/user-attachments/assets/3a800c3c-97f5-48f8-8138-0a3ef4a73152" />
<img width="960" alt="Frame 15276-3" src="https://github.com/user-attachments/assets/7d3b84a6-36fa-4a46-9f45-f7b0323c5520" />
<img width="960" alt="Frame 15276-4" src="https://github.com/user-attachments/assets/6a042621-4f81-46a0-975e-cd1b292cb22a" />
<img width="960" alt="Frame 15276-5" src="https://github.com/user-attachments/assets/2b66cc09-5298-43d1-8a78-551c4e9dfe97" />
<img width="960" alt="Frame 15276-6" src="https://github.com/user-attachments/assets/a9ea2ec9-acb4-41c8-88a6-f055c0050835" />
<img width="960" alt="Frame 15276-7" src="https://github.com/user-attachments/assets/47ee7b3d-5980-4c9c-b280-0dbeb66c23ef" />
<img width="960" alt="Frame 15276" src="https://github.com/user-attachments/assets/2211e581-08d0-4788-a431-2217aefa389f" />

```[tasklist]
### CFA Interest
- [ ] ETSL (high priority)
- [ ] Magister (high priority)
- [ ] Bingel DC (high priority)
- [ ] NEON (high priority)
- [ ] MAX (high priority)
- [ ] Clickedu (low priority)
- [ ] ItsLearning: We are eliminating this pattern at the moment because of accessibility and performance issues. If everything goes well, we won't re-introduce it.
```

### Requirement of CFA's
**Icons and Elements**
- Support icons or elements (e.g., badges) before and after expand/collapse arrows.
- Allow additional items next to titles or on the right (e.g., quantities, status indicators).

**Checkboxes**
- Enable checkbox functionality for items.

**State Indications**
- Include clear visual states for active, hover, and other user interactions.

**Structure and Levels**
- Support up to 6 levels for complex structures, like Tables of Content.
- Provide space for supplementary information, such as page numbers.

**Expand/Collapse**
- Include options for expanding/collapsing all sections at once.
- Distinguish between clickable section titles and the expand/collapse chevron icon.

```[tasklist]
### Needed components and patterns
- [ ] tree component
- [ ] tree node component
- [ ] https://github.com/sl-design-system/components/issues/1621
```

### Inspiration
- 

### Tasks

When working on the **documentation** for this component please have a look at the review comments that were left on this PR, to have a starting point: https://github.com/sl-design-system/components/pull/1647

**Comment by anna-lach** [comment]
Guides (helper lines) should be visible by default and it should be possible to hide them.
