### ISSUE TITLE
[Chromatic] Improve snapshot setup

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1112]
```[tasklist]
### Tasks
- [x] Improve theme setup so they show all the components that are ready for that theme
- [x] Make all "All stories" so that they indeed show all the possible options of the component, preferably in a table. The story shouldn't include any input (controls)
- [x] only snapshot 'all' stories
```

**Comment by Diaan** [comment]
https://www.chromatic.com/blog/story-modes-are-here/
