### ISSUE TITLE
[V1] Switch component

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#114]
| <div align="left">**What is the problem we are solving and why?**  |
| ------------- |
|As a user, I want to change the state of system functionalities and preferences quickly, so I can use the product how I want to use it|

The switch component is part of the MVP of the SL Design System. A toggle switch is a digital on/off switch. Toggle switches are used for changing the state of system functionalities and preferences.

```[tasklist]
### Tasks
- [ ] https://github.com/sanomalearning/design-system/issues/219
- [ ] https://github.com/sanomalearning/design-system/issues/220
- [ ] https://github.com/sanomalearning/design-system/issues/223
- [ ] https://github.com/sl-design-system/components/issues/486
- [ ] https://github.com/sl-design-system/components/issues/576
- [ ] https://github.com/sl-design-system/components/issues/494
- [ ] https://github.com/sl-design-system/components/issues/495
- [ ] https://github.com/sl-design-system/components/issues/582
- [ ] https://github.com/sl-design-system/components/issues/566
- [ ] https://github.com/sl-design-system/components/issues/489
- [ ] https://github.com/sl-design-system/components/issues/568
- [ ] https://github.com/sl-design-system/components/issues/482
- [ ] https://github.com/sl-design-system/components/issues/633
- [ ] https://github.com/sl-design-system/components/issues/754
- [ ] https://github.com/sl-design-system/components/issues/780
```
