### ISSUE TITLE
[Search Field] Research

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1140]
```[tasklist]
### Tasks
- [x] Research, what do we have right now?
- [x] What do other design systems have?
- [x] Set up requirements (together with the team)
- [x] [Acceptance criteria] Create wireframes
- [x] [Acceptance criteria] First draft of documentation
- [x] [Acceptance criteria] Put in #240
```

**Comment by DanielleRameau** [comment]
Delete current branch and create a new one with proper name docs instead of feature.
