### ISSUE TITLE
[Search Field] UI Design

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1144]
```[tasklist]
### Tasks
- [x] Create UI Design
- [x] Create tokens for SL light
- [x] Create tokens for SL dark
- [x] Create Figma sheet for copying to other themes
```
