### ISSUE TITLE
[Data grid] Research

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1149]
```[tasklist]
### Tasks
- [x] Hand-over Magister
- [x] Workshop with CFA's - what is the core functionality and what are nice to haves for version 2?
- [x] Deliver list features for Danielle
- [x] First draft requirements (based on contribution) + our requirements (discuss with SLDS Team)
- [x] [Acceptance criteria] Create wireframe of core functionalities
- [x] [Acceptance criteria] Put in #771
```
