### ISSUE TITLE
[Data grid] UI Design of Grid Table

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1150]
## Grid Table
A grid table is a structured layout for displaying tabular data. This component presents large data sets in a way that is easy to scan, understand, and manipulate. A data table typically consists of three main parts: row headers (column headers), data rows, and footer rows.

```[tasklist]
### Cell Type
- [ ] **Cell width** based on a percentage (Hug, 1x, 2x, 3x, 4x and expand) (do not implement, designers can do this manually, add in the documentation how this works)
- [x] Dividers (horizontal & Vertical)
- [x] Focus Ring
```

```[tasklist]
### Cell Type
- [x] Text cell (left aligned)
- [x] Numbers cell (right aligned)
- [x] Drag cell (Handle)
- [x] Selectable cell
- [x] Header Column cell
- [x] Group Title cell
- [x] Actions Row cell (Contextual row buttons)
- [x] Input Field cell
- [x] Avatar cell
- [x] Slot cell
```

```[tasklist]
### Cell Variants (Row Variants)
- [x] Default cells
- [x] Header cells
- [x] Footer cells
- [x] Group cells
```

```[tasklist]
### Row Height
- [ ] **Vertical Adjustment:** Provide a fixed or adaptable height property toggle. Then, the designer can choose how the row behaves to the content.
- [ ] **Top Alignment:** By default, The rows are vertically aligned to the centre. The vertical alignment changes to the top when the row exceeds 3 line heights.
```

```[tasklist]
### Row Styling
- [x] Grid border
- [x] Density (Compact, Condense and Relaxed)
- [x] Zebra styling (Only Rows)
- [x] Column Dividers only for Column Headers
- [x] Row Dividers
```

```[tasklist]
### Scrolling Related
- [ ] **Sticky column header** must be sticky with the top of the grid container. But, when the user scrolls the page, the headers must be visible while the Grid is visible.
- [ ] **Sticky Group header** rows are also sticky to the top, but they stack below the header row and swap between each other when the next group reaches the top of the container.
- [ ] **Sticky Columns**, the leftmost column needs to be fixed when there is a horizontal overflow.
- [ ] **Sticky Actions** must always be visible. When the grid overflows, they are sticky at the container's right.
- [ ] **Overflow Actions** In mobile screens, the actions buttons condense in a contextual menu.
```

```[tasklist]
### Tasks
- [x] Review Designs of Magister, what can be reused
- [x] Create contextual tokens
- [x] Make it ready for dev first
- [x] Finetune component for use in Figma
```

**Comment by DanielleRameau** [comment]
@arecuenco-dsgn place requirements for features in this issue

**Comment by DanielleRameau** [comment]
Fixed in Diana's grid finetuning branch.
