### ISSUE TITLE
[Combobox] Research

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1154]
```[tasklist]
### Tasks
- [x] First draft requirements (discuss with SLDS Team)
- [x] [Acceptance criteria] Create a wireframe of core functionalities
- [x] [Acceptance criteria] Put in #258
- [x] Create survey
- [x] Survey Results from CFAs
- [x] [Acceptance criteria] First draft of documentation
- [ ] https://github.com/sl-design-system/components/issues/1388
```
