### ISSUE TITLE
[Combobox] Development

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1156]
```[tasklist]
### Tasks
- [ ] Create combobox based on requirements #1156
- [ ] develop various modes first (inspiration: https://role-components-git-konnorrogers-650642-konnor-rogers-projects.vercel.app/components/combobox/#list-autocomplete-combobox)
- [ ] See UI Design in Figma
```
