### ISSUE TITLE
[Component status/resources] Implement design of component details page

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1159]
https://www.figma.com/file/fpvv1aBzMNVTbJaFHhraB9/SLDS---Documentation-Website?type=design&node-id=3298%3A62818&mode=design&t=lQSNv3kPbtvNuy6U-1

```[tasklist]
### Tasks
- [x] run import icon to get access to the custom storybook icon
- [x] component detail page in different break points
- [x] planned and new badge in navigation
- [x] add readme file for designers so they can change the status in the navigation
```
