### ISSUE TITLE
[Button Group] Research

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1160]
**Acceptance Criteria Segmented Control:**
https://www.figma.com/design/PGb66fVN325tu0IngRka66/SL-Component-Research?node-id=1333-2743&t=rnD3TqWd6mLKOGyZ-4

```[tasklist]
### Tasks
- [x] Research, what do we have right now?
- [x] What do other design systems have?
- [x] Set up requirements (together with the team)
- [x] Create wireframes
```
