### ISSUE TITLE
[Toggle Group] UI Design

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1161]
```[tasklist]
### Tasks
- [x] Create UI Design
- [x] Create tokens for SL light
- [ ] Create Figma sheet for copying to other themes
- [ ] contact Jeroen when you start with design to test the tokens for the borders
- [x] It can reuse the (toggle) button tokens
- [x] have a extra ook at pill shaped buttons
- [x] focus state of button in the middle of the group, how does it work?
```
