### ISSUE TITLE
[Toggle Group] Development

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1162]
```[tasklist]
### Tasks
- [ ] dont highlight the label only isolation, only in cobination with the toggle group
- [ ] update naming from button group to toggle group
- [ ] multi-select (option) and single select (default) property
```

![image](https://github.com/user-attachments/assets/62452f52-bf61-41e7-8435-bd15d9b2fae6)
