### ISSUE TITLE
[Split Button] UI Design

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1166]
```[tasklist]
### Tasks
- [ ] Create UI Design
- [ ] Create tokens for SL light
- [ ] Create tokens for SL dark
- [ ] Create Figma sheet for copying to other themes
```
