### ISSUE TITLE
[Toggle button] UI Design

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1172]
```[tasklist]
### Tasks
- [x] Create UI design based on requirements
- [x] Create tokens for SL light
- [x] Create tokens for SL dark
- [x] Create Figma sheet for copying to other themes
```
