### ISSUE TITLE
First draft RICE Framework for SLDS

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1176]
```[tasklist]
### Tasks
- [x] Create calculations for RICE
- [x] Find out which tool we use to do the calculation
- [x] Create a confluence page about the framework, what it is, how we use it, and more about the process
- [x] Present to the SLDS team and discuss next steps
```
