### ISSUE TITLE
Button improvements

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1177]
```[tasklist]
### Tasks
- [x] Color contrast buttons SL light
- [x] Color contrast SL Dark
- [x] Typography in Sesame themes to bold (in buttons)
```
