### ISSUE TITLE
Make button bar available in all themes

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1193]
```[tasklist]
### Tasks
- [x] copy tokens to all themes
- [x] copy components to all figma libraries
- [x] publish libraries
- [x] bug fix: check divider of accordion in all themes
- [ ] #1221
- [x] [Magister] change border-radius of dialog
```
