### ISSUE TITLE
[Enabling new requests] Organise kick-off/brainstorm about new requests

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1198]
```[tasklist]
### Tasks
- [x] Who can do new requests?
- [x] How can do requests?
- [x] Where can they do new requests?
- [x] Which information should they provide?
- [x] How should we inform CFA's
```
