### ISSUE TITLE
[Component status/resources] Storybook

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1202]
Discover if we can provide component status and link to documentation within a story. (investigate)

```[tasklist]
### Tasks
- [x] link to documentation (nice to have)
- [ ] link to latest package in GitHub (nice to have, can be found on documentation website as well)
- [ ] https://github.com/sl-design-system/components/issues/1247
- [ ] the latest version of the components (nice to have, can be found on documentation website as well)
- [ ] Changelog of a component (nice to have, can be found on documentation website as well)
- [ ] readme file?
- [ ] provide outcome of discovery and create a new story based on the outcome
```
