### ISSUE TITLE
[bug][sl-select] ellipsis on longer text (sl-select-button and sl-select-option)

### ISSUE THREAD

**Issue by kssc4567** [sl-design-system/components#1209]
**Describe the bug**
When option value is longer than the sl-select width, the text expands the button causing CLS.
When option value is longer than the sl-select width, the expanded option value goes beyond the border.

**To Reproduce**
1. Add sl-select and sl-select-option with long text
2. Click on expand
3. Scroll down to long text option

**Expected behavior**
When option value text is longer than the sl-select width, use ellipsis to cut text in button
When option value text is longer than the sl-select width, wrap text in option in a way it doesnt cross border

**Screenshots**
<img width="143" alt="image" src="https://github.com/sl-design-system/components/assets/163280493/0d30d90e-dc8a-4e91-9472-e4fc7ee79939">
<img width="200" alt="image" src="https://github.com/sl-design-system/components/assets/163280493/7bf9713d-6f7b-4b36-b96a-ed6745268a4b">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 123

**Additional context**
- product: @sl-design-system/max@0.1.7
- component: @sl-design-system/select@0.0.27
- Angular 15

```[tasklist]
### Tasks
- [ ] test if words break correctly with the right language set
- [ ] add overflow-wrap: break-word? (probably not the right solution)
- [ ] show in storybook example of how to set width of select
```

**Comment by Diaan** [comment]
we will be adding this to sl-select-option:
```
  word-break: auto-phrase;
  overflow-wrap: break-word;
  hyphens: auto;
```

It is however important that the language (`lang=nl` or `lang=en`) is set correctly; the browser uses this language to analyze the words and place the hyphens.

The width of the select can be set in the css of the cfa by setting it directly on the component, like on our documentation page: https://sanomalearning.design/categories/components/select/
