### ISSUE TITLE
[POC] Status badge in readme.md files (automatically)

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1212]
Create a single source of truth for the status of a component and show it in component packages.
### Tasks
- [ ] show in read me files
- [x] show in 11ty
- [x] show in storybook

**Comment by jpzwarte** [comment]
So I look into this and found the following:

In order to have a dynamic badge in the README, you need a web service that returns an image based on a query parameter. There are some available services for this, but those do not allow for the kind of badge we want. We would have to create our own service to do this. That is not trivial. So for now i think it's easiest to just update the status in multiple places.
