### ISSUE TITLE
[Scannable navigation] 

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1223]
### Tasks
- [ ] see categories in storybook
- [ ] create ui design of sections in component navigation
- [ ] implement design on documentation website
