### ISSUE TITLE
[Badge] add subtle variant

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1226]
Add a border in the badge component. Right now there are some a11y issues regarding contrast.

![Image](https://github.com/sl-design-system/components/assets/111998351/35bb371b-bf47-4516-bb01-0d9ca70ff5a2)

```[tasklist]
### Tasks
- [x] current badge will be called 'bold badges'
- [x] add 'subtle badges' with a lighter background
- [x] add variant in SL theme
- [ ] https://github.com/sl-design-system/components/issues/1042
- [ ] https://github.com/sl-design-system/components/issues/1280
- [x] Copy to all themes (+ styling)
- [x] add variant in code
- [x] explain in documentation when to use strong or subtle badges
- [x] update figma options table in  documentation
```
