### ISSUE TITLE
[Form] Solving label

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1231]
```[tasklist]
### Tasks
- [x] Check if old label is used in all form control components (check in all themes) (Alvaro) and come up with a solution
- [ ] https://github.com/sl-design-system/components/issues/1235
- [x] Current form controls get the deprecared status (put status in name) (Danielle)
- [x] Create new form control components with the new label and make available in all themes (Danielle)
- [x] Hide deprecated form controls when publishing (Danielle)
- [x] inform designers about the update (Danielle)
```

![Image](https://github.com/sl-design-system/components/assets/111998351/144379da-8510-4d38-963c-a7d6fcdc0185)

**Comment by arecuenco-dsgn** [comment]
Here are the new control forms (the components and the guides):
- SL Light: https://www.figma.com/design/1oIVcD9VMbOtLXYp48ehsA/Sanoma-Learning-Light-mode?node-id=8218-25132&t=WGrtGNOfXySLtEPS-4
- SL Dark: https://www.figma.com/design/gnrOGCDlfN2c8HnPk12g6w/Sanoma-Learning-Dark-mode?node-id=2120-18124&t=lAu7iQVq7exuA5X1-4
