### ISSUE TITLE
Add all the Icon sizes in Figma

### ISSUE THREAD

**Issue by arecuenco-dsgn** [sl-design-system/components#1254]
- [x] Apply sl.icon to all themes
- [x] Expand sizes of sl.icon component in Editorial Suite themes and apply current tokens

The Icon component in Figma doesn't have all the sizes the final component supports. Also, I found that the large icons don't have the same sizes.

The sizes that are available in the Storybook:
| Size  | Code | Figma |
| ------------- | ------------- | ------------- |
| xs  | 12px  | None  |
| sm  | 14px  | 14px  |
| md  | 16px  | 16px  |
| lg  | 20px  | 18px  |
| xl  | 24px  | 24px  |
| 2xl  | 32px  | None  |
| 3xl  | 48px  | None  |
| 4xl  | 64px  | None  |

This issue was created from a message of Maria Trybuś on the Slack sl-design-system channel:
[https://sanoma.slack.com/archives/C03SA9HUUA3/p1716199122317319](https://sanoma.slack.com/archives/C03SA9HUUA3/p1716199122317319)
![Image](https://github.com/sl-design-system/components/assets/77982487/e7ef22ea-5f12-4617-a689-7a3be11b3b3e)

```[tasklist]
### Tasks
- [ ] https://github.com/sl-design-system/components/issues/1307
```
