### ISSUE TITLE
[Enabling new requests] Create new forms in GitHub

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1260]
```[tasklist]
### Tasks
- [x] add 'new component' form in GitHub
- [x] update 'feature request' form in GitHub
- [x] add 'figma toolkit' form in GitHub
- [x] add 'documentation' form in Github
- [x] update 'General' form in GitHub
- [x] update 'bug report' form in GitHub
```
