### ISSUE TITLE
Badge changes - issue and request

### ISSUE THREAD

**Issue by MDWSanoma** [sl-design-system/components#1280]
### Provide a general summary of the issue here

Badge styling issues, little padding and no right icon

### 🤔 Expected Behavior?

I'd expect the badge component to have more padding, or the option to modify the padding. It looks a bit bulky on smaller and medium sizes. A padding sm, md, lg option would be nice.

Also, we'd like the option to either have a dismiss button on the right side, (cross icon), or an option for icon-end.

### 😯 Current Behavior

Very narrow padding, no icon on right side

### 💁 Possible Solution

More padding on smaller sizes, or smaller icon
or Option for padding size (sm, md, lg)

Option for icon-start and icon-end

### 📷 Screenshots

<img width="100" alt="Screenshot 2024-05-24 at 11 17 00" src="https://github.com/sl-design-system/components/assets/121878399/08e0eea3-01fd-424b-af30-5e75674bd609">

### 📎 Link to Figma

https://www.figma.com/design/YZeBneflpJkX3KXSyvMrqP/Magister-Light-mode?m=auto&node-id=1444-42838&t=fOzM5v2ckY1BWmn1-1

### 🎨 Your Theme(s)

Magister
```[tasklist]
### Tasks
- [x] Add padding
- [x] remove icon only badge?
- [x] implement in all themes
- [x] update in documentation
```

**Comment by DanielleRameau** [comment]
We don't add an icon back option due to inconsistency reasons.
