### ISSUE TITLE
Wrong color of warning button

### ISSUE THREAD

**Issue by Martrybus** [sl-design-system/components#1283]
### Provide a general summary of the issue here

Hi! For the Editorial theme, we used to have a different color for warning buttons, it was yellow (#ffb200), and now it is brown. Is it possible to bring back the previous yellow color for the warnings? The brown color that we have now looks too much as a danger color.

### 🤔 Expected Behavior?

Please change the color of warning buttons to #ffb200 (color.palette.warning.base), as it was before.

### 😯 Current Behavior

I've noticed that the primary warning button has chnaged its color to brown,
<img width="343" alt="warning " src="https://github.com/sl-design-system/components/assets/170721457/86ff2d7d-0071-4880-a47b-88f03e5e5d82">

https://www.figma.com/design/S5QgDy8X9eqhvECPANSZMM/Editorial-Suite-designs?node-id=6558-140237&t=Z7M0XLggjlc5e4S7-1

### 🖥️ Steps to Reproduce

- Open ES theme
- take sl-button component 
- chnage it to the warning state
- the current color of the button is not the one it used to be a couple of weeks ago

### What browsers are you seeing the problem on? (only for bugs in code)

Chrome

### What operating system are you using?

windows

### 🧢 Your product/team

ETSL/Editorial Suite

### 🎨 Your Theme(s)

Editorial Suite
```[tasklist]
### Tasks
- [x] look into the warning shades, make it a bit more 'saturated',
- [ ] make the warning color fit in the inline message but also 'eye-pleasing' if it's used it on its own
- [ ] update components with warning colors in figma
```
