### ISSUE TITLE
Typography Bingel INT

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1291]
Change font in Bingel INT app
```[tasklist]
### Tasks
- [ ] add Proxima Nova
- [ ] update all components (don't publish)
- [ ] discuss components with Bingel INT
```
