### ISSUE TITLE
additional states of Select component

### ISSUE THREAD

**Issue by Martrybus** [sl-design-system/components#1295]
### Provide a general summary of the feature here

Hello! 
As for the Select field component, in the nearest future Editorial Suite would need 3 additional options: 1) **multiselect** 2) **select with a date picker (calendar)** 3) select with numbers picker

### 🤔 Expected Behavior?

1) The most important for ES is to have a multiselect component in addition to the usual select. User will be able to pick multiple values from a drop down menu.
2) Then, we would need a field with a date picker (calendar)
3) Finally, we would need a field allowing to select numbers only, and go higher or lower using the arrows (examples in the screenshots below)

### 😯 Current Behavior

Currently in the DS, there is just a normal select field with a drop down menu. 
In our old ES style, we had all the needed states of this component, but we are trying to switch to the DS entirely.

### 🔦 Context

We are currently switching all our application to the design system. Hovewer, we cannot replace the Select fields, because we have more 'states' of Select, especially in the important for the users Metadata panel. 

In this panel, in our old styles, we had 4 different types of Select: _usual dropdown, multiselect, select with date picker, select with number picker._

Right now we are blocked and cannot use the Select component before all that 4 states are ready. This causes some inconsistencies in styling, as some components that we use are already from the DS, and some are from 'old' Editorial Suite style.
<img width="300" alt="select 1" src="https://github.com/sl-design-system/components/assets/170721457/5590b625-3579-42f1-a735-bd754b6f1e8b">
<img width="220" alt="select 2" src="https://github.com/sl-design-system/components/assets/170721457/c2bc140b-35b9-46d6-b846-a256cb8e18e9">
<img width="290" alt="select 3" src="https://github.com/sl-design-system/components/assets/170721457/162345bd-dab0-4e6d-ab51-2e06211accd8">

### 💻 Examples

I attached the examples of the required select states: a) multiselect 2) date picker 3) number picker:

<img width="146" alt="image" src="https://github.com/sl-design-system/components/assets/170721457/82a4a815-0ad9-418b-8939-dfa1ee771565">
<img width="140" alt="image" src="https://github.com/sl-design-system/components/assets/170721457/868ca084-97bc-4989-ab7e-487f31a57803">
<img width="161" alt="image" src="https://github.com/sl-design-system/components/assets/170721457/23160767-e0ea-46fa-994b-1e619631ae9a">

### 🧢 Your Product/Team

Editorial Suite
```[tasklist]
### Tasks
- [ ] Split requests up in request board (new components)
- [ ] to create a date picker we also need a calendar and month component (add on request board)
- [ ] date range and single date
```

**Comment by DanielleRameau** [comment]
@Martrybus these are already requests for these components, I'll add ETSL to the list as a CFA that is interested so it will have a higher priority.

**Comment by Martrybus** [comment]
@DanielleRameau thank you!
