### ISSUE TITLE
[POC] Progress indicator

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1358]
```[tasklist]
### Tasks
- [x] UI of the progress bar
- [x] Make progress bar available in all themes
- [ ] Development of the progress bar
- [x] First draft of documentation
```
