### ISSUE TITLE
[Tags] Development of tags

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1387]
```[tasklist]
### Tasks
- [x] add tag stack component
- [x] see requiments in #258
- [x] add read-only tags
- [x] truncated tags?
```
