### ISSUE TITLE
Add better 3xl size to avatar

### ISSUE THREAD

**Issue by jpzwarte** [sl-design-system/components#1432]
### Provide a general summary of the feature here

`<dna-avatar>` has an `xl` size that has no equivalent in `<sl-avatar>`. This is a problem in Magister where the XL size is used in various places.

![CleanShot 2024-08-06 at 12 46 53@2x](https://github.com/user-attachments/assets/651d97de-819d-4a04-83d1-f35355beaf78)

### 🤔 Expected Behavior?

-

### 😯 Current Behavior

-

### 🔦 Context

-

### 🧢 Your Product/Team

Magister
```[tasklist]
### Tasks
- [x] add a bigger size avatar to our scale, see example jeroen. (160px)
- [ ] https://github.com/sl-design-system/components/issues/1489
- [x] updated in code
- [x] update documentation
```
