### ISSUE TITLE
[Data grid] the basics - code part

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1518]
```[tasklist]
### Tasks
- [ ] https://github.com/sl-design-system/components/issues/1526
- [ ] https://github.com/sl-design-system/components/issues/1530
- [ ] https://github.com/sl-design-system/components/issues/1529
- [ ] https://github.com/sl-design-system/components/issues/1520
- [ ] https://github.com/sl-design-system/components/issues/1528
- [ ] https://github.com/sl-design-system/components/issues/1527
```
