### ISSUE TITLE
[Panel] UI Design

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1570]
```[tasklist]
### Tasks
- [x] see requirements in #1293
- [x] Is using new contextual tokens
- [x] create sheet in figma
- [x] do we need any new tokens? Let's see how to intergrate this within contextual tokens
- [x] add slot component to intergrate toolbar component in the panel heading
```
```[tasklist]
### UI Key Features
- [x] Indicator Position Left/Right
- [x] Header Slot
- [x] Header Actions
- [x] Header Title Sub-Component (Style)
- [x] Body Slot
- [x] Panel Examples
- [x] Apply new contextual tokens base on the last meeting (Elevation: None, Raised and Sunken)
```
