### ISSUE TITLE
[Panel] Development

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1572]
```[tasklist]
### Tasks
- [x] add boolean for border (for all elevation properties)
- [x] elevation properties: default, raised and sunken
- [x] add elevation property raised and sunken
- [x] toggle: start, end
- [x] panel is not collapsable by default
```

**Comment by anna-lach** [comment]
Conclusions after the 'Design progress meeting':

- in the code there should be no slot for the badges (above or below the title/subtitle)
- there should be a slot for prefix, suffix, title and subtitle in the header
