### ISSUE TITLE
Contextual token upgrade

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1577]
```[tasklist]
### Tasks
- [ ] fix 'transparent' token (token is missing)
- [ ] https://github.com/sl-design-system/components/issues/1506
- [ ] https://github.com/sl-design-system/components/issues/1629
```

**Comment by jpzwarte** [comment]
I'm working on refactoring the button styling and i've run into some issues:

1. SL theme now uses Roboto font; however, that font does not have a semibold/600 font weight. The closest is medium/500.  As you can see from the screenshots below, 500 or 600 matters. At 600, the browser starts to emulate the font weight. Should we have a theme specific token that we can use in CSS for the "bold" weight? So that would then have the value of `500` for the SL theme?
![CleanShot 2024-11-21 at 08 33 51@2x](https://github.com/user-attachments/assets/01d05836-c757-4ad2-bde6-f2474224082b)
![CleanShot 2024-11-21 at 08 33 45@2x](https://github.com/user-attachments/assets/ed0afb8a-c1d1-4c95-a130-7b2438efc54f)

2. `border-color: var(--sl-color-utility-transparent-000);` is not the same as `border-color: transparent`. This is noticeable in the visual size of the buttons: you can see in the screenshots below that the former seems to have a less height. 
![CleanShot 2024-11-20 at 15 28 26@2x](https://github.com/user-attachments/assets/29ab65d7-6afb-4f1a-bda2-2f2c47d42799)
![CleanShot 2024-11-20 at 15 25 45@2x](https://github.com/user-attachments/assets/60dc8fc3-f2ee-44cd-961a-8b3c7b1d1712)

3. I don't see a `default` variant in Figma anymore. Do we still have that style or is that now obsolete?

4. The tokens for the inverted buttons are incorrect. I think this is due to how the tokens are transformed to CSS.

```json
"hover": {
  "value": "{color.palette.grey.000}",
  "type": "color",
  "$extensions": {
    "studio.tokens": {
      "modify": {
        "type": "alpha",
        "value": "{opacity.dark.300}",
        "space": "lch"
      }
    }
  },
  "description": "Use for the background while hovering of primary actions that appear to have no background in idle state. Such as outline and ghost buttons."
}
```

5. There doesn't seem to be any difference on hover (other than underline) or active states for link buttons. Is that intentional?

6. Icon only buttons in some themes (magister for one) are already round. I assume this will break with the new styling? (i don't have an issue with that perse). By default, those magister icon-only buttons would now be square.

**Comment by jpzwarte** [comment]
Update on issue number 4: this is a limitation of the `ts/color/modifiers` transform at the moment. I have to disable `outputReferences` in the plugin and the the correct color is outputted. However, that also doesn't output references to other CSS custom properties anymore, making it harder to debug.
