### ISSUE TITLE
[Toolbar] Set requirements

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1586]
Set requirements for toolbar component. (this component will be used in grid and panel)

### Tasks
- [x] Discussion with the Jeroen to set-up the requirements
- [ ] responsive behavior of toolbar in panel and grid
- [x] Create wireframes to visualize solution
- [x] How does it work on mobile? Actions vs a toolbar in rich text editor

**Here is the acceptance criteria:** [Main Toolbar Issue](https://github.com/sl-design-system/components/issues/1585)
