### ISSUE TITLE
[Utility] Create an aria live container on page

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1597]
```[tasklist]
### Tasks
- [x] CFA's can be used for example when a chat message comes in
- [x] Create a POC
- [x] Create solution on outcome of POC
- [x] Create an API or service to send messages to the live aria
```

**Comment by Diaan** [comment]
https://www.sarasoueidan.com/blog/accessible-notifications-with-aria-live-regions-part-1/
https://www.sarasoueidan.com/blog/accessible-notifications-with-aria-live-regions-part-2/
