### ISSUE TITLE
[Calendar] Contribution

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1600]
Contribution: https://www.figma.com/design/o1ZlCUh6LyicB6xBu2GRmC/DNA-Library?node-id=3950-229139&t=mrNF7I6kRn6DUsom-4

### Tasks
- [x] Invite Floor for refinement
- [ ] [Calendar] Improvements Figma Component
- [ ] [Calendar] Link design to contextual tokens and make available in all themes
- [ ] [Calendar] Update documentation
- [ ] [Calendar] Finetune code
