### ISSUE TITLE
Prototype issues with SL Select

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1646]
### Provide a general summary of the issue here

During a user testing session with a Figma prototype, we encountered an issue with the SL Design System select menu component. While it functioned correctly in our browsers, the respondent experienced unexpected behavior during testing.

To avoid disruptions in upcoming tests, I unlinked the problematic components. However, I’ve recreated the screen where the issue occurred, specifically in the "Actief binnen" filter. You can access the prototype [here](https://www.figma.com/proto/1yroCKkROktqhRCP2wwlzB/Bingel-International-UX?page-id=7213%3A3970&node-id=14511-184515&node-type=frame&viewport=-10469%2C-14545%2C0.44&t=8FinYxrfTft7ze6F-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=14511%3A184515&show-proto-sidebar=1) or the Figma file [here](https://www.figma.com/design/1yroCKkROktqhRCP2wwlzB/Bingel-International-UX?node-id=14511-184515&t=MIIqUHacyMYyvuFh-4).

### 🤔 Expected Behavior?

The select menu should function consistently, maintaining its layout and selection across all browsers.

### 😯 Current Behavior

The component failed to behave as expected in 

- Chrome: Version 131.0.6778.86 (Official Build) (64-bit)
- Edge: Version 131.0.2903.63 (Official Build) (64-bit)
- Microsoft Edge for Business, 131.0.2903.51

### 📷 Screenshots

![image](https://github.com/user-attachments/assets/31ca6b64-fdea-47fc-8779-b1b51245f0cd)
![Image](https://github.com/user-attachments/assets/f5d7918e-1636-489a-98ef-e27de2e24d3e)

### 📎 Link to Figma

https://www.figma.com/design/1yroCKkROktqhRCP2wwlzB/Bingel-International-UX?node-id=14511-184515&t=MIIqUHacyMYyvuFh-4

### 👤 Your name

Karol Woźniak

### 🎨 Your Theme(s)

Magister
```[tasklist]
### Tasks
- [ ] Contact Elżbieta Kurzyk, she is able to reproduce it
- [ ] https://sanoma.slack.com/archives/C03SA9HUUA3/p1732636141625839
- [ ] put a note in the component, mention that they need to detach the instance the component for prototyping
```

**Comment by RoaldBoerema** [comment]
@vv0zny Sorry for the delay, but I was waiting for an answer from Figma. I didn't get one from them directly, but talked to other people in the community with the same problems. Unfortunately this is a longstanding bug (5 years) that Figma is aware of but it doesn't seem to be high up on their todo list. It probably is a custom font issue (Proxima Nova in your case). Making the component Nested doesn't seem to help either. We are encountering more and more issues with Nested components that go beyond three layers (sometimes even two). With the refactoring of our components we try to take the Nested issue into account. Detaching components could be a short term solution, but isn't something we would normally advise. The proposed solution from Figma for the custom fonts isn't really that great.

Here is their answer:

> It appears that you have encountered a long standing bug that the engineers are aware of.
> 
> If this is something you would be interested in, I would be able to create a bug report for the engineers to investigate, however, due to it being a long standing bug, we will not be able to provide an estimated timeline for a resolution.
> 
> I understand that this is not an ideal solution, but please know that we are actively working on improving our platform and addressing issues like this. We appreciate your understanding and patience as we strive to provide a better experience for our users.
> 
> As a workaround for this issue, we have the following:
> · Replace the custom fonts with a Google font, which will be available on every device that runs Figma prototypes
> · Have the client/whoever is looking at the prototype install the missing custom font
