### ISSUE TITLE
[Number Field] Setting final requirements

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1655]
```[tasklist]
### Tasks
- [x] see requirements CFA
- [x] check current number fields within other products and design systems
- [x] accessibility criteria
- [x] wireframes
- [x] acceptance criteria
- [ ] first draft of documentation
```
