### ISSUE TITLE
[Tree view] Setting final requirements

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1656]
```[tasklist]
### Tasks
- [x] discuss a11y issues with ItsLearning, what is their new pattern?
- [x] set final acceptance criteria
- [x] check other products and design systems
- [x] first draft of documentation
```
