### ISSUE TITLE
Refactoring Custom Icons Set-up

### ISSUE THREAD

**Issue by arecuenco-dsgn** [sl-design-system/components#1658]
Move the custom icons to one file
```[tasklist]
### Tasks
- [ ] [UI] Create a new file for Icons in the SLDS 2.0 folder
- [ ] [UI] Create a page in the new file for each product
- [ ] [UI] Copy the custom icons from each product to there pages
- [ ] [Code] Change the set-up of the custom icons in the SLDS
```

**Comment by Diaan** [comment]
Icons needs to be components in order to be exported correctly:

<img width="128" alt="Image" src="https://github.com/user-attachments/assets/bfc42d18-ce1d-4b0d-875b-1f7167607690" />
`storybook-test` works, `storybook` doesn't.
