### ISSUE TITLE
[Combobox] Accessibility

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1666]
### Tasks
- [x] Find a way to make combobox accessible in all screenreaders
- [x] Implement this solution
- [ ] once you edit the field but do not confirm the selected items will not change and will remain the same (it will clear the input if you didn't confirm it)
- [ ] when you are leaving the field it should reflect what it will send to the server
