### ISSUE TITLE
[Number Field] Create UI Design

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#1681]
```[tasklist]
### Tasks
- [x] Create UI based on accptance criteria
- [x] Make UI ready DEV
- [x] Finetune for prototyping
- [x] Make available in SLDS 2.0 library
```
