### ISSUE TITLE
Launch button component on sanomalearning.design

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#171]
# Launch button component on sanomalearning.design
**This user story is part of https://github.com/sanomalearning/design-system/issues/160**

|<div align="left">**What is the problem we are solving and why?**|
|-------------|
|As a user, I want to have accessible and a consistent buttons, so I can perform my aactions quickly| 
|As a developer, I want to have an easy to use button component, so I can quickly implement actions in the user interface of the product|
|As a designer, I want to have clear UX documentation and an easy to use Figma component of a button, so I can quickly create actions in my prototypes| 

## Description
When the button component is ready we need to make it available on the documentation website.

```[tasklist]
### Tasks
- [x] UX documentation (D)
- [x] technical documentation (DEV)
- [x] accessibility documentation (D or DEV)
- [x] Make template for visuals and create them for all docs (A)
- [ ] Launch on sanomalearning.design (DEV)
- [ ] Mention on Slack
- [ ] Which input do we need from dev side? Please communicate this properly.
- [ ] all components except button should be disabled or marked as coming
```

**Comment by DanielleRameau** [comment]
https://confluence.sanomalearning.com/pages/viewpage.action?pageId=364112420

**Comment by Diaan** [comment]
https://custom-elements-manifest.open-wc.org/analyzer/getting-started/
