### ISSUE TITLE
Icon tokens

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#205]
| <div align="left">**What is the problem we are solving and why?**  |
| ------------- |
|As a user, I want to have a consistent icon usage in the user interface, so I can quickly scan de product and see what I have to do to fulfill my tasks| 
|As a designer, I want to have an icon set with clear documentation, so I can create prototypes with consistent icon usage| 

```[tasklist]
### Tasks
- [x] https://github.com/sanomalearning/design-system/issues/72
- [x] https://github.com/sl-design-system/components/issues/76
- [x] https://github.com/sanomalearning/design-system/issues/213
- [x] https://github.com/sanomalearning/design-system/issues/239
- [ ] https://github.com/sanomalearning/design-system/issues/221
```
