### ISSUE TITLE
Component detail page

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#207]
| <div align="left">**What is the problem we are solving and why?**  |
| ------------- |
|As a user of the SL Design System, I want to find clear documentation for the components that I want to use, so I can  successfully implement components in any product|

```[tasklist]
### Tasks
- [x] https://github.com/sanomalearning/design-system/issues/35
- [x] https://github.com/sanomalearning/design-system/issues/50
- [x] https://github.com/sanomalearning/design-system/issues/214
- [x] https://github.com/sanomalearning/design-system/issues/252
- [x] Update url when navigating with tabs at the top of page (easy for linking/bookmarking to "code" tab for example)
- [ ] https://github.com/sl-design-system/components/issues/832
```
