### ISSUE TITLE
First draft UX documentation Radio group

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#225]
**Description**
Radio buttons are graphical user interface elements that allow user to choose only one option from a predefined set of mutually exclusive options.

**Requirements**
- available in different sizes (sm|md|lg)
- labels
- text and label are clickable

**States**
- idle
- active
- checked/selected
- disabled
- focus
- hover
- invalid

**Radio group**
- orientation? 
- keyboard navigation: https://www.w3.org/WAI/ARIA/apg/patterns/radiobutton/
```[tasklist]
### Tasks
- [x] What is an input field? / introduction text
- [x] Types
- [x] Anatomy
- [x] Behaviors
- [x] How to use
- [x] Content
- [x] Interaction (accessibility)
- [x] Behavior (accessibility)
- [x] Recommendations (accessibility)
- [x] Add a draft title or issue reference here
```

**Comment by DanielleRameau** [comment]
https://confluence.sanomalearning.com/pages/viewpage.action?pageId=411581406
