### ISSUE TITLE
First draft UX documentation text area

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#232]
## Description
Create first draft of UX documentation regarding the text area. A text area lets a user input a longer amount of text than a standard text field #194 .

## Requirements
- available in different sizes
- labels
- validation
- support prefix and or suffix
- help text

## States
- idle
- hover
- focus
- active
- disabled
- invalid
- valid
- read-only

```[tasklist]
### Tasks
- [ ] What is an text area? / introduction text
- [ ] What are the key points?
- [ ] Types
- [ ] Anatomy
- [ ] Behaviors
- [ ] How to use
- [ ] Responsiveness
- [ ] Content
- [ ] Interaction (accessibility)
- [ ] Behavior (accessibility)
- [ ] Labeling (accessibility)
- [ ] Recommendations (accessibility)
- [ ] Add a draft title or issue reference here
```
