### ISSUE TITLE
[V1] Checkbox component

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#235]
| <div align="left">**What is the problem we are solving and why?**  |
| ------------- |
|As a user, I want to select multiple items, so I can choose from a list of individual items| 

## Description
Checkboxes allow users to select multiple items from a list of individual items, or to mark one individual item as selected.

```[tasklist]
### Tasks
- [ ] https://github.com/sanomalearning/design-system/issues/236
- [ ] #67
- [ ] https://github.com/sanomalearning/design-system/issues/237
- [ ] https://github.com/sanomalearning/design-system/issues/317
- [ ] https://github.com/sanomalearning/design-system/issues/342
- [ ] https://github.com/sanomalearning/design-system/issues/315
- [ ] https://github.com/sanomalearning/design-system/issues/316
- [ ] https://github.com/sanomalearning/design-system/issues/377
- [ ] https://github.com/sl-design-system/components/issues/588
- [ ] https://github.com/sanomalearning/design-system/issues/331
- [ ] https://github.com/sanomalearning/design-system/issues/340
- [ ] https://github.com/sanomalearning/design-system/issues/318
- [x] Finetune UX documentation of checkbox
- [x] Finetune multi-brand checkbox
- [x] Launch checkbox in Figma Toolkit
- [x] Launch checkbox on Github
- [x] Make everyone aware that the checkbox is available
- [x] remove valid state
- [ ] https://github.com/sl-design-system/components/issues/760
- [ ] https://github.com/sl-design-system/components/issues/665
- [ ] https://github.com/sl-design-system/components/issues/877
- [ ] https://github.com/sl-design-system/components/issues/889
```
