### ISSUE TITLE
First draft UX documentation of select

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#271]
```[tasklist]
### Tasks
- [ ] What is a select? / introduction text
- [ ] What are the key points?
- [ ] Types
- [ ] Anatomy
- [ ] Behaviors
- [ ] How to use
- [ ] Responsiveness
- [ ] Content
- [ ] Interaction (accessibility)
- [ ] Behavior (accessibility)
- [ ] Labeling (accessibility)
- [ ] Recommendations (accessibility)
- [ ] Add a draft title or issue reference here
```

**Comment by DanielleRameau** [comment]
duplicate see #601
