### ISSUE TITLE
Development of select

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#272]
The select component is part of the MVP of the SL Design System. A select gives users the ability to make a single selection from a number of options.

Check Miro board design ideation:
https://miro.com/app/board/uXjVP6TtQdI=/?share_link_id=419677033460

**Use cases**
- in a form
- in a page
- when it's pre selected
- when it is empty
- when you unselect it
- Select: icon + item (single select) 
- Select: item (single select)
- The amount of options determines what kind of control you need to use

**Features**
- Positioning strategy popover (pop-up aligned with current selection)
- Design for default selection
- Keyboard navigation
- Auto sizing to length of longest option

**Types** (can be different based on the outcome of the use cases)
- default
- subtle
- none (no box)

**States**
- idle
- hover
- active
- focus
- invalid
- disabled
- readonly

```[tasklist]
### Tasks
- [ ] Development
- [ ] Writing tests
- [x] Add support for multiple box shadows in one token. right now the translator ignores those shadows.
- [x] keyboard navigation options first goes through all optiongroups, then separate options.
```

**Comment by Diaan** [comment]
For the dropdown use `<dialog popover>`

**Comment by Diaan** [comment]
There's a problem using `size.3xs` values in the box-shadow for the listbox boxshadow. In those values the `px` is included. In other places we set a box-shadow the `px` is not included in the value of the token, and we add it when transforming the tokens to css. When using `size.3xs` we get a calculated value in the browser like `2px px` this is invalid and so we see no box shadow.

![Image](https://github.com/sl-design-system/components/assets/1351956/ee290682-adee-4db4-bd11-5e9dc539f2cb)

Also the naming of the tokens doesn't seem to be consistent between core and SL-light theme

**Comment by Diaan** [comment]
Todo:
- [ ] keyboard navigation options first goes through all optiongroups, then separate options.
