### ISSUE TITLE
First draft UX documentation of dialog

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#273]
## Acceptance criteria
#266 

```[tasklist]
### Tasks
- [ ] What is an dialog? / introduction text
- [ ] What are the key points?
- [ ] Types
- [ ] Anatomy
- [ ] Behaviors
- [ ] How to use
- [ ] Responsiveness
- [ ] Content
- [ ] Interaction (accessibility)
- [ ] Behavior (accessibility)
- [ ] Labeling (accessibility)
- [ ] Recommendations (accessibility)
- [ ] Add a draft title or issue reference here
```
