### ISSUE TITLE
First draft UX documentation of avatar

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#289]
Discuss acceptance criteria

```[tasklist]
### Tasks
- [ ] What is a popover? / introduction text
- [ ] What are the key points?
- [ ] How to use
- [ ] Types
- [ ] Anatomy
- [ ] Behaviors
- [ ] Responsiveness
- [ ] Content
- [ ] Interaction (accessibility)
- [ ] Behavior (accessibility)
- [ ] Labeling (accessibility)
- [ ] Recommendations (accessibility)
```

**Comment by DanielleRameau** [comment]
duplicate see #604
