### ISSUE TITLE
Multi-brand checkboxes, radio buttons

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#367]
```[tasklist]
### Tasks
- [ ] #340
- [ ] #339
- [ ] #330
- [ ] https://github.com/sanomalearning/design-system/issues/317
- [ ] https://github.com/sanomalearning/design-system/issues/329
- [ ] https://github.com/sanomalearning/design-system/issues/331
- [ ] https://github.com/sanomalearning/design-system/issues/342
- [ ] https://github.com/sanomalearning/design-system/issues/341
```
