### ISSUE TITLE
Finetuning checkboxes and radio buttons

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#399]
After reviewing the validation of checkboxes en radio button we noticed we created unnessecary states.

- Valid can be removed since we don't show validate states after submit
- Invalid checked can be removed since a invalid state will only pop up when it is unchecked

```[tasklist]
### Tasks
- [ ] Place current approach (within figma) in archive (can be used in a later stage when we need a checkbox in tests/exercises)
- [ ] Remove valid and invalid checked from the options in the different themes
- [ ] Remove tokens in all themes
```

**Comment by DanielleRameau** [comment]
after discussion we decided to keep it as is.
