### ISSUE TITLE
Finetuning ItsLearning components

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#400]
```[tasklist]
### Tasks
- [x] [ ]Icon only button should be a square (see figma comment)
- [x] Icon only button should have a squared shape (see figma comment)
- [x] border witdth is 2px for outline buttons
- [ ] https://github.com/sl-design-system/components/issues/406
- [x] icon only should be square
- [x] warning default button color contrast with white background is not enough
```
