### ISSUE TITLE
remove padding in link button

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#406]
What to do with hover and active state?

```[tasklist]
### Tasks
- [x] link button without padding (text underline on hover)
- [x] current link button will be renamed to 'ghost'
- [x] Place link button in Figma
- [x] Make link button available for all themes
- [x] Issue with Kampus and Neon link button background
```

**Comment by DanielleRameau** [comment]
@jpzwarte Is this solved within your POC?

**Comment by jpzwarte** [comment]
> @jpzwarte Is this solved within your POC?

Yes
