### ISSUE TITLE
multi-brand form controls

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#409]
```[tasklist]
### Tasks
- [ ] #397
- [ ] https://github.com/sl-design-system/components/issues/481
- [ ] https://github.com/sl-design-system/components/issues/482
- [ ] #199
- [ ] https://github.com/sl-design-system/components/issues/485
- [ ] https://github.com/sl-design-system/components/issues/486
- [ ] #396
- [ ] https://github.com/sl-design-system/components/issues/488
- [ ] https://github.com/sl-design-system/components/issues/489
- [ ] #394
- [ ] #395
- [ ] https://github.com/sl-design-system/components/issues/492
- [ ] #201
- [ ] https://github.com/sl-design-system/components/issues/494
- [ ] #202
- [ ] https://github.com/sl-design-system/components/issues/493
- [ ] https://github.com/sl-design-system/components/issues/495
- [ ] #200
```

**Comment by DanielleRameau** [comment]
hind font: <link rel=“stylesheet” href=“https://use.typekit.net/qod6igq.css“> (NEON theme)
