### ISSUE TITLE
Implementation focus ring in Figma

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#470]
```[tasklist]
### Tasks
- [x] Button (all themes brands + dark and light mode)
- [x] Checkbox (all themes brands + dark and light mode)
- [x] Radio (all themes brands + dark and light mode)
- [x] Text field (all themes brands + dark and light mode)
- [x] Text area (all themes brands + dark and light mode)
- [x] Select (all themes brands + dark and light mode)
- [x] Switch (all themes brands + dark and light mode)
- [x] Clean up old focus ring (all themes brands + dark and light mode)
```

**Comment by DanielleRameau** [comment]
@RoaldBoerema could you give an update about the status?
