### ISSUE TITLE
Contextual tokens

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#483]
**Problem**
Right now we need to insert all values manually in all states of our components. 

**Solution**
In a ideal world the component tokens are already referred to contextual tokens before you create a new theme. In this case you don't have to edit the component tokens but only the contextual tokens.

**Example**
Global variants (body, block, elevation etc)
Component variants (default, accent, informative, invalid, valid, warning, disabled)
Background
Foreground
Border
Defined in all states
Etc.  

So surface.component.informative.background.idle
Surface.global.body.accent.background

```[tasklist]
### Tasks
- [ ] https://github.com/sl-design-system/components/issues/446
- [ ] https://github.com/sl-design-system/components/issues/513
- [ ] https://github.com/sl-design-system/components/issues/484
- [ ] https://github.com/sl-design-system/components/issues/479
- [ ] https://github.com/sl-design-system/components/issues/512
- [ ] Discuss adding "surface" and "elevation" tokens to core
- [ ] Discuss naming for buttons solid/outline/ghost/link; "solid" caused quite a lot of discussion
- [ ] Add the control tokens to core & all the themes
- [ ] Add button component tokens to core & all the themes
- [ ] Add a core-dark version
- [ ] # Future - Add radio component tokens - Add checkbox component tokens - etc.
- [ ] https://github.com/sl-design-system/components/issues/20
- [ ] https://github.com/sl-design-system/components/issues/328
```

**Comment by DanielleRameau** [comment]
see #1005
