### ISSUE TITLE
Development of component overview page

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#511]
```[tasklist]
### Tasks
- [x] make cards for components (with image)
- [x] make sections (with heading for a groups of components)
- [x] available in light and dark mode
- [x] animation on hover: zoom in similar to the one on the homepage
- [x] make sure the page is responsive in the same way as the design
- [x] make the card that are still in PoC/coming state not clickable and use a placeholder image
- [x] exclude 'Guidelines' from the navigation for now
- [x] improve code sections styling in the dark mode version of 'Guidelines'
- [x] Paragraphs should have max-width of 640px
```

Out of scope:
- footer
- side menu

Design: 
https://www.figma.com/file/fpvv1aBzMNVTbJaFHhraB9/SL---Web-Generator?type=design&node-id=1230%3A2500&mode=dev
