### ISSUE TITLE
[V1] Breadcrumbs

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#528]
## User Story
As a Sanoma Learning Design System user, I want a user-friendly Breadcrumbs Component that can effectively handle various use cases across our educational products. This Breadcrumbs Component should be adaptable to convey:

## Definition
Breadcrumbs displays a hierarchical trail of links, aiding navigation by showing users their path within a website or app. It helps users understand their current position and easily backtrack to previous levels.

## Key Points
- Navigation aid showing user's path.
- Displays hierarchical trail of links.
- Provides context about current position.
- Enables easy backtracking.
- Enhances user experience with clear navigation.

## Acceptance Criteria
![breadcrumbs-elements](https://github.com/sl-design-system/components/assets/77982487/bea93de6-1524-42eb-bff8-ea067e608a64)

**Elements**
| Name  | Optional |
| ------------- | ------------- |
| Level Label | Yes | 
| Separator | Yes |
| Overflow Menu | No |
| Panel Slot | No |

**Variants**
- Home Level
- Link Level
- Current Level

**States**
- Idle
- Hover
- Active
- Disabled

## Behaviours
![breadcrumbs-shortening](https://github.com/sl-design-system/components/assets/77982487/9cd9117a-5c21-4ca0-aaa5-44d08cea244f)
Shortening Levels (Number): When there are links with long labels, it’s possible to set up maximum width to control this behaviour. The user can see the whole label with the tooltip if the label is truncated.
![breadcrumbs-truncations](https://github.com/sl-design-system/components/assets/77982487/f9f349fe-fe03-48be-a48c-f9216e0b976e)
Truncation Levels (2 links): When there are a lot levels links, it only display the last 2 levels to keep everything simple.
![breadcrumbs-mobile](https://github.com/sl-design-system/components/assets/77982487/ccaa83f7-13a2-46b7-899c-b0fc7d8099b1)
In Mobile, the contextual menu appear from the bottom to more accessible the list. Also this match the visuals mobile standards. 

## Keyboard Navigation
![breadcrumbs-keyboard](https://github.com/sl-design-system/components/assets/77982487/501e0ee4-8725-487e-bd1d-37b16dcfd62a)
- Tab to move between levels, starting from the 1st level link and moving forward to the last level link.
- Space or Enter, if there is hiding levels with an overflow menu, you can open the dropdown menu with the hide levels pressing these keys and continue moving with the Tab.
- Shift + Tab to move to the previous.

## Figma Links
- [Figma Breadcrumbs Component Research](https://www.figma.com/file/PGb66fVN325tu0IngRka66/SL-Component-Research?type=design&node-id=512-6282&mode=design&t=KWA57Wt0p7ITimG7-4)

## Reference Links
- [Truncation](https://pencilandpaper.io/articles/breadcrumbs-ux/)

```[tasklist]
### Tasks
- [ ] https://github.com/sl-design-system/components/issues/744
- [ ] https://github.com/sl-design-system/components/issues/781
- [ ] https://github.com/sl-design-system/components/issues/782
- [ ] https://github.com/sl-design-system/components/issues/783
```

**Comment by anna-lach** [comment]
@arecuenco-dsgn 

1. <img width="193" alt="image" src="https://github.com/sl-design-system/components/assets/111562742/2f246ae6-fb24-40e3-9952-59948dbe7ff3"> those element are more like items / elements of the breadcrumbs, than variants? I guess there will be only one variant here?

4. Should the `current level` not be a link (not clickable)?

7. What's the behaviour, when the link is too long? Adding `...` at the end of the link or in the middle? Showing tooltip with the truncated link on hover/focus?

10. Do we want to have `home` icon always shown or it should be customisable or it can be other icon as well or icon and text?
