### ISSUE TITLE
Make website more ready to use

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#531]
```[tasklist]
### Tasks
- [x] getting started for dev (GitHub) 🐨
- [x] Clean up comment documentation in code 🐨
- [x] Create pages for components that are ready 🦘
- [x] Add live example on component detail page 🦘
- [ ] Check stories of components for references to things we are fixing in this story.
- [x] fix position of popovers (select + tooltip)🐨
- [x] fix loading of icon 🐨
- [x] fix size of check icons in checkbox 🐨
- [ ] check position of arrow on popover 🐨
- [x] generating component's properties for multiple selectors 🦘
- [x] move the generated properties to the code tab 🦘
- [x] Fill the "button" page with content (first draft) from https://confluence.sanomalearning.com/pages/viewpage.action?pageId=364112420 🐨
- [x] add text between component title and "slots/properties/methods" titles (just generic "Component has a range of props to define the experience in different use cases." 🦘
- [x] disable links to PoC components in menu and used "coming" badge 🦘
- [x] Exclude FAQ from navigation 🦘
```

**Comment by Diaan** [comment]
🐨 = Diana will work on this

**Comment by Diaan** [comment]
Positioning of popover doesn't work when one of the parents is using css translate.
- https://github.com/floating-ui/floating-ui/issues/1815

**Comment by Diaan** [comment]
https://proud-water-0d02ee203-555.westeurope.2.azurestaticapps.net/
