### ISSUE TITLE
Multi-brand form controls

### ISSUE THREAD

**Issue by Diaan** [sl-design-system/components#550]
```[tasklist]
### Tasks
- [ ] https://github.com/sl-design-system/components/issues/580
- [ ] https://github.com/sl-design-system/components/issues/581
- [ ] https://github.com/sl-design-system/components/issues/582
- [ ] #199
- [ ] https://github.com/sl-design-system/components/issues/485
- [ ] https://github.com/sl-design-system/components/issues/486
- [ ] #395
- [ ] https://github.com/sl-design-system/components/issues/567
- [ ] https://github.com/sl-design-system/components/issues/568
- [ ] https://github.com/sl-design-system/components/issues/576
- [ ] https://github.com/sl-design-system/components/issues/575
- [ ] #200
- [ ] https://github.com/sl-design-system/components/issues/566
- [ ] https://github.com/sl-design-system/components/issues/565
- [ ] #394
- [ ] https://github.com/sl-design-system/components/issues/492
- [ ] #201
- [ ] https://github.com/sl-design-system/components/issues/494
- [ ] #202
- [ ] https://github.com/sl-design-system/components/issues/493
- [ ] https://github.com/sl-design-system/components/issues/495
```
