### ISSUE TITLE
checkbox, radio button and textfield refer to button tokens

### ISSUE THREAD

**Issue by RoaldBoerema** [sl-design-system/components#574]
**Describe the bug**
Checkbox and radio button refer to button tokens  

**To Reproduce**
Please check out core.json INPUT and TEXTFIELD sections

**Expected behavior**
If the goal is to have consistency between component we should refer to base tokens instead of other components.

```[tasklist]
### Tasks
- [x] Checkbox & Radio spacing tokens
- [x] Checkbox & Radio Border tokens
- [x] Text Fields spacing tokens
- [x] Text Fields Border tokens
- [ ] https://github.com/sl-design-system/components/issues/635
```

**Comment by arecuenco-dsgn** [comment]
Additional context

```
"input": {
"option": {
"block": {
"md": {
"value": "{space.button.outline.block.sm}",
"type": "spacing",
"description": "space.button.solid.block.md"
},
"lg": {
"value": "{space.button.outline.block.sm}",
"type": "spacing",
"description": "space.button.solid.block.lg"
}
},
"inline": {
"md": {
"value": "{space.button.outline.block.sm}",
"type": "spacing",
"description": "space.button.solid.inline.md"
},
"lg": {
"value": "{space.button.outline.block.sm}",
"type": "spacing",
"description": "space.button.solid.inline.lg"
}
},
"gap": {
"md": {
"value": "{space.button.outline.block.md}",
"type": "spacing",
"description": "{space.button.gap.md}"
},
"lg": {
"value": "{space.button.outline.block.md}",
"type": "spacing",
"description": "{space.button.gap.lg}"
}
}
},
"textField": {
"block": {
"md": {
"value": "{space.xs} + {border.width.button.default}",
"type": "spacing",
"description": "space.button.solid.block.md"
},
"lg": {
"value": "{space.sm} - {border.width.button.default}",
"type": "spacing",
"description": "space.button.solid.block.lg"
}
},
"inline": {
"md": {
"value": "{space.md} - {border.width.button.default}",
"type": "spacing",
"description": "space.button.solid.inline.md"
},
"lg": {
"value": "{space.lg} - {border.width.button.default}",
"type": "spacing",
"description": "space.button.solid.inline.lg"
}
},
```

**Comment by DanielleRameau** [comment]
This branch should be merged
