### ISSUE TITLE
Tracking Component Status/resources

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#578]
**Description**
As a design system user, I want to easily track the status of individual components and find the resources on the documentation website, so that I can confidently choose and use stable and ready-to-use elements for my projects.

### Discovery
- [ ] https://github.com/sl-design-system/components/issues/1118
- [ ] https://github.com/sl-design-system/components/issues/1119
- [ ] https://github.com/sl-design-system/components/issues/1120
- [ ] https://github.com/sl-design-system/components/issues/1159
- [ ] https://github.com/sl-design-system/components/issues/1212
- [ ] https://github.com/sl-design-system/components/issues/1201
- [ ] https://github.com/sl-design-system/components/issues/1202
- [ ] https://github.com/sl-design-system/components/issues/1203
- [ ] https://github.com/sl-design-system/components/issues/1211

**Comment by Diaan** [comment]
add a "dateStatusChanged" property to `<component-name>.json` so we can show a dot or star, or something else to indicate that the STATUS of the component has changed: Coming->Preview->Stable. To trigger users to look at which components they can start using (either in preview or stable).
