### ISSUE TITLE
Make dialog available in all themes

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#591]
- Make an overview of all tokens that need to be added to all files. 
- Make a sheet in SL them that can be pasted in all themes.

```[tasklist]
### Tasks
- [x] Create sheet of dialog to copy to other themes (alvaro)
- [x] Clickedu light
- [x] ItsLearning light
- [x] Max online light
- [x] NEON light
- [x] NEON dark
- [x] Bingel INT light
- [x] Bingel DC light
- [x] Kampus light
- [x] TEAS light
- [ ] https://github.com/sl-design-system/components/issues/609
- [ ] https://github.com/sl-design-system/components/issues/615
```

**Comment by DanielleRameau** [comment]
Alvaro makes screenshots of the involved tokens.
