### ISSUE TITLE
Nowa Era theme

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#595]
```[tasklist]
### Tasks
- [x] Make copy of NEON light
- [x] Change accent color values
- [x] Publish theme in Figma
- [ ] Publish theme in Storybook
```
