### ISSUE TITLE
Basic Documentation of Text Field

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#597]
Wait for #196 
```[tasklist]
### Tasks
- [ ] UX documentation (review)
- [ ] technical documentation (review)
- [ ] accessibility documentation (review)
- [ ] Installation guide (in code)
```

**Comment by Diaan** [comment]
The "Behaviour" heading is missing for the text field on confluence: https://confluence.sanomalearning.com/pages/viewpage.action?pageId=411583121

Don't we need this here? 
My suggestion would be to keep the documentation as uniform as possible; so describe all the same properties at least, that makes comparing them also easier.

**Comment by Diaan** [comment]
- [ ] aria text
- [ ] placeholder images
