### ISSUE TITLE
Make inline message available for all themes

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#609]
```[tasklist]
### Tasks
- [x] Create a sheet to copy to all themes
- [x] Make available for all themes
- [x] clickedu
- [x] itslearning
- [x] max online
- [x] NEON light
- [x] NEON dark
- [x] Bingel INT
- [x] Bingel DC
- [x] Kampus
- [x] TEAS
- [ ] Change font-size of description to text.md.normal (check with dev)
```
