### ISSUE TITLE
UI of skeleton component

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#618]
```[tasklist]
### Tasks
- [x] add tokens for skeleton state
- [x] token for background color
- [x] token for shimmer effect (color)
- [x] token for border-radius (refer to to default border-radius by default)
- [x] add token for minimum-height
- [x] add shape for avatars
- [x] add shape for paragraphs
```

**Comment by DanielleRameau** [comment]
change effect color token @RoaldBoerema
