### ISSUE TITLE
Development of spinner

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#624]
```[tasklist]
### Tasks
- [x] create dev based on ui
- [x] implement reduced motion thing
- [ ] try to reuse DNA
- [x] spin line
- [x] spin shadow
```

The DNA spinner: https://gist.github.com/jpzwarte/3736ae2bedfb64044e9575d14aff86d8
