### ISSUE TITLE
UI of card

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#628]
```[tasklist]
### Tasks
- [x] Figma documentation for card
- [x] rewrite/remap fonts so they actually work
- [x] card border width is not a token
```
