### ISSUE TITLE
Research + Wireframe badge

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#637]
share your insights in confluence
```[tasklist]
### Tasks
- [x] ux research: what the difference between a badge and a tag?
- [x] Wireframe
- [x] Facilitate workshop with team to discuss acceptance criteria for V1
- [x] Create final acceptance criteria (place them in feature #278)
```

**Comment by DanielleRameau** [comment]
Shoelace (inspiration)
