### ISSUE TITLE
Research insights + Wireframe of Spinner

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#648]
## User Story
As a Sanoma Learning Design System user, I want a versatile and user-friendly Spinner Component that can effectively handle various use cases across our educational products. This Spinner Component should be adaptable to convey:

## Definition
Spinner is used to display the loading state or a section of a page. As a visual indicator that a process is happening in the background but the interface is not yet ready for interaction.

## Key Points
- Used when some part of the page takes 2–10 seconds to load.

## Acceptance Criteria

**Elements**
| Name  | Optional |
| ------------- | ------------- |
| Spinner | No |

**Sizes** 
- Extra-Small
- Small
- Medium (Default)
- Large

**Layout**
- Inline (Default)

**A11y**
- Spinners provide feedback to users that the system is working but don’t give any indication on how long users will have to wait; therefore, they are best used when the page takes 2–10 seconds to load.

## Figma Links
- [Figma Spinner  Component Research](https://www.figma.com/file/PGb66fVN325tu0IngRka66/Component-Research?type=design&node-id=317-1590&mode=design&t=m0kvuGk6YIoSBfHd-4)

```[tasklist]
### Tasks
- [x] See what other products have right now (make overview in figma)
- [x] research spinner in button
- [x] research spinner on page (when skeleton is not possible)
- [x] Wireframe of spinner (?)  focus more on animations and what the best practices are
- [x] Write acceptance criteria for feature
```

**Comment by Diaan** [comment]
In the refinement we came to the conclusion that the spinner doesn't need a label. This is changed in figma by @arecuenco-dsgn but not yet here. That is the reason I removed it.
