### ISSUE TITLE
Switch: support label *after* control on the same line

### ISSUE THREAD

**Issue by jpzwarte** [sl-design-system/components#667]
Support the layout where the label is shown after the control on the same line.

There have been multiple requests from different parties for this.

<img width="282" alt="CleanShot 2023-09-26 at 10 12 48@2x" src="https://github.com/sl-design-system/components/assets/3968/6f0f65f0-c635-4fb3-a31c-cbf712cc00f8">

TODO: figure out how to toggle this layout.

```[tasklist]
### Tasks
- [ ] Make this feature available in code (it's already available within Figma)
- [ ] Update documentation: label on the left when you have a list with switches label on the right: when you use an inline or stand-alone switch + vertical alignment is used within forms.
- [ ] Naming Default: start (label left), reversed: end (label right)
```
