### ISSUE TITLE
Update homepage

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#681]
```[tasklist]
### Tasks
- [x] remove guidelines card
- [x] Place news card on the left side (check design)
- [x] Place button getting started for designers and developer underneath hero text
- [x] animate news visual
- [x] make the badge on the component detail page a link to the release
```

**Comment by Diaan** [comment]
try to make the badge on the component detail page a link to the release
