### ISSUE TITLE
Wireframe of Alert component

### ISSUE THREAD

**Issue by arecuenco-dsgn** [sl-design-system/components#717]
```[tasklist]
### Tasks
- [x] Wireframe
- [x] Facilitate workshop to create acceptance criteria
- [x] Create final acceptance criteria for V1
- [ ] Update description for V2 alert (Figma Research)
- [ ] https://github.com/sl-design-system/components/issues/742
```
