### ISSUE TITLE
Documentation of MVP (Basic Content)

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#718]
We only work in the basic information of the component. We work directly into the GitHub page, to speed up the launch of each documentation page. Them we'll create another epic to finetune (visuals) the docs.

```[tasklist]
### Tasks
- [ ] https://github.com/sl-design-system/components/issues/428
- [ ] https://github.com/sl-design-system/components/issues/745
- [ ] https://github.com/sl-design-system/components/issues/604
- [ ] https://github.com/sl-design-system/components/issues/592
- [ ] https://github.com/sl-design-system/components/issues/944
- [ ] https://github.com/sl-design-system/components/issues/600
- [ ] https://github.com/sl-design-system/components/issues/946
- [ ] https://github.com/sl-design-system/components/issues/947
- [ ] https://github.com/sl-design-system/components/issues/605
- [ ] https://github.com/sl-design-system/components/issues/601
- [ ] https://github.com/sl-design-system/components/issues/602
- [ ] https://github.com/sl-design-system/components/issues/621
- [ ] https://github.com/sl-design-system/components/issues/599
- [ ] https://github.com/sl-design-system/components/issues/598
- [ ] https://github.com/sl-design-system/components/issues/597
- [ ] https://github.com/sl-design-system/components/issues/952
```
