### ISSUE TITLE
Improvements in current form controls

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#725]
The overall scope of this issue is to simplify, cleanup and improve the existing form controls. 

- Move all form related code into its own `@sl-design-system/form` package
- Instead of having multiple mixins/controllers all related to form controls (`FormControlMixin`, `HintMixin` and `ValidationController`), move them all into a single mixin
- Remove custom validators and instead provide a `setCustomValidity` method for setting a custom validation message; this matches other web component libraries (Material for example) but also the native form validation API
- Unify hint & error rendering by wrapping them in their own components
- Extract even more form control code by creating a new `<sl-form-field>` component: this simplifies the form controls even more in that they *only* render the actual form component, nothing else. This makes handling focus for example easier. And it move the hint & error rendering from every form control into a single component.

With the exception of the last item, all these step have already been done for `<sl-text-field>`.

```[tasklist]
### Tasks
- [x] Move all form related code into the `@sl-design-system/form` package (label, hint, error, mixins)
- [ ] Migrate each component to use the `FormControlMixin` from the new form package instead of the shared one
- [ ] Remove support for custom validations from the form controls
- [ ] Either use `ElementInternals` *or* `<input>`, not both
- [ ] DRY rendering of hints & errors through the use of `<sl-hint>` and `<sl-error>`
- [ ] Add a new `<sl-form-field>` component and move hint & error rendering into that, simplifying form controls even more
```

**Comment by jpzwarte** [comment]
@DanielleRameau definitely a duplicate of #752 ; please close.
