### ISSUE TITLE
Make Tab component available for all themes

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#731]
```[tasklist]
### Tasks
- [x] Create figma page to copy to all themes
- [x] Clickedu
- [x] ItsLearning
- [x] Magister light
- [x] Magister Dark
- [x] Max Online
- [x] MyVanin
- [x] Neon light
- [x] Neon dark
- [x] Bingel INT
- [x] Bingel DC
- [x] Kampus
- [x] TEAS
- [x] Editorial Suite
- [x] My Digital Book
- [ ] SL Dark mode
```
