### ISSUE TITLE
Research insights + Wireframe of Cards

### ISSUE THREAD

**Issue by arecuenco-dsgn** [sl-design-system/components#733]
DNA: https://dna.iddinkgroup.com/?path=/story/core_layout-card-examples--api
ItsLearning: [https://www.figma.com/file/9P9V9x20hxLdL3NWzoQ2ZU/Cards?type=design&node-id=0-1&mode=design](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.figma.com%2Ffile%2F9P9V9x20hxLdL3NWzoQ2ZU%2FCards%3Ftype%3Ddesign%26node-id%3D0-1%26mode%3Ddesign&data=05%7C01%7Cdanielle.rameau%40sanoma.com%7Cc3c2daba5b4a49f7158808dbdf8dc8e3%7C4d5a48993bae4dc59ea0ba540b354430%7C0%7C0%7C638349572283362438%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=g4Im7yCiOY3ziCbZUrjGv%2Ff4i9BsH5bytIPyp%2FOSi20%3D&reserved=0)

```[tasklist]
### Tasks
- [x] Overview of all cards components of SL products
- [x] Gather UX insights for card component
- [x] Wireframe
- [x] Create acceptance criteria for Card together with the Team
- [x] Plan meeting with team thursday afternoon
```
