### ISSUE TITLE
Button padding

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#749]
Ghost, outline and link buttons use solid padding tokens.
```[tasklist]
### Tasks
- [ ] https://github.com/sl-design-system/components/issues/849
- [ ] https://github.com/sl-design-system/components/issues/798
- [ ] https://github.com/sl-design-system/components/issues/851
- [x] double check
```

```[tasklist]
### Tasks
- [x] SL Light
- [x] SL Dark
- [x] Bingle INT Light
- [x] Bingle DC Light
- [x] Clckedu Light
- [x] Its learning Light
- [x] Kampus Light
- [x] Magister Light
- [x] Magister Dark
- [x] Max Light
- [x] Neon Light
- [x] Neon Dark
- [x] Teas Light
- [x] Myvanin Light
- [x] Nowa era Light
- [x] Editorial suite Light
- [x] My digital book Light
- [x] Utbilding Light
```

**Comment by DanielleRameau** [comment]
![Image](https://github.com/sl-design-system/components/assets/111998351/4dcdb195-f9da-4de8-b1c8-49aa1e3bc18a)

**Comment by RoaldBoerema** [comment]
Changing the button to default in the inline message won't work in ClickEdu, Default button is purple. We need to add a info color button.
