### ISSUE TITLE
Refactor all form controls

### ISSUE THREAD

**Issue by Diaan** [sl-design-system/components#752]
For each component we need to:
- [x] Refactor form controls to use the new `@sl-design-system/form` `FormControlMixin`
- [x] Remove hint property & rendering from the form controls
- [x] Simplify focus handling in the form controls

```[tasklist]
### Tasks
- [ ] https://github.com/sl-design-system/components/issues/814
- [ ] https://github.com/sl-design-system/components/issues/820
- [ ] https://github.com/sl-design-system/components/issues/822
- [ ] https://github.com/sl-design-system/components/issues/821
- [x] https://github.com/sl-design-system/components/issues/819
- [ ] https://github.com/sl-design-system/components/issues/833
- [ ] https://github.com/sl-design-system/components/issues/837
- [ ] https://github.com/sl-design-system/components/issues/839
- [ ] https://github.com/sl-design-system/components/issues/840
- [ ] https://github.com/sl-design-system/components/issues/841
- [ ] https://github.com/sl-design-system/components/issues/855
- [ ] https://github.com/sl-design-system/components/issues/856
- [ ] https://github.com/sl-design-system/components/issues/878
- [ ] https://github.com/sl-design-system/components/pull/888
```
