### ISSUE TITLE
Refactor Switch (including design changes?)

### ISSUE THREAD

**Issue by Diaan** [sl-design-system/components#754]
```[tasklist]
### Tasks
- [x] Figure out what to do for `<sl-switch>` since hint rendering is different than other form controls.
- [ ] Refactor switch to work with new Form Field component
- [ ] place hint outside of the container (figma)
- [ ] remove hint from switch component (code)
- [ ] add reversed version of switch (code, already there in figma)
```

**Comment by DanielleRameau** [comment]
@Diaan explain what the issue is

**Comment by Diaan** [comment]
<img width="468" alt="image" src="https://github.com/sl-design-system/components/assets/1351956/ad9b8966-0435-4e36-9b95-e6bbf03df0aa">
This alignment is not possible when the hint is not in the same container/wrapper as the title and switch button.
With the new form field setup the hint is no longer able to be part of the same container, so this layout is not possible.
In Figma you can mimic this setup/limitations; there needs to be a container around label AND toggle, THAT container can be on the same level as the hint.

**Comment by DanielleRameau** [comment]
![Image](https://github.com/sl-design-system/components/assets/111998351/f09737de-09aa-4dd5-9778-bf34bea7dc4b)
