### ISSUE TITLE
Theme fixing

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#766]
```[tasklist]
### Clickedu
- [x] Checkbox: not able to select focus state
- [x] Checkbox + radio: missing border.width.input.option
- [x] Focusring: missing border.width.focusring.default
```

```[tasklist]
### Open tasks
- [ ] https://github.com/sl-design-system/components/issues/587
```

```[tasklist]
### ItsLearning
- [x] missing: borderRadius.focusring.checkbox
- [x] missing: border.width.input.option
- [x] popover: color.select.item.active.background
- [x] popover: borderradius.select.listbox
- [x] popover:icon.typeset.fontsize.2xs (should be xs, remap)
- [x] popover:text.tooltip.text.tip
- [ ] select: color.select.item.default.placeholder
- [x] select: border.width.button.default
- [ ] select: border.width.select.listbox
- [ ] select: border.width.divider
- [x] select:border.width.select-copy.listbox
- [ ] select:boxshadow.select.listbox
- [ ] select: text.select.selectbox.text.md
- [ ] select:text.select.selectbox.title.md
- [ ] select:text.select.selectbox.title.lg
- [ ] select:text.select.selectbox.text.lg
```

```[tasklist]
### Tasks
```

**Comment by DanielleRameau** [comment]
Create pull request
