### ISSUE TITLE
Development of button bar

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#769]
```[tasklist]
### Tasks
- [x] Implement tokens of button bar
- [x] small gap for icon only ghost buttons (4px)
- [x] default gap (8px)
- [x] Example of mobile button bar
- [x] Example of mobile behavior: by default the button bar is wrapped, it is optional the fill out the buttons in the container
```

**Comment by Diaan** [comment]
Switch to vertical mode is done by css token, from the place where the button bar is used. Right now you need 2 properties, try to find a way to do it with one property. 
https://lea.verou.me/blog/2020/10/the-var-space-hack-to-toggle-multiple-values-with-one-custom-property/
use this until style queries are available
