### ISSUE TITLE
Design button bar

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#770]
Tokens we need:
- `--sl-button-bar-align`: default alignment of the button-bar; does a theme have the button aligned on the left or on the right?
- `--sl-button-bar-inline-gap`: the horizontal space between buttons
- `--sl-button-bar-block-gap`: the vertical space between buttons (when the buttons do not fit on a single line)

The other question is whether the spacing should be different if a button-bar contains only buttons of a particular type (icon-only for example).

```[tasklist]
### Tasks
- [x] Define behavior of button bar for all buttons (spacing)
- [x] Create tokens (and clean up the old ones)
- [x] Create Button Bar Component in Figma
```

**Comment by DanielleRameau** [comment]
see #1170
