### ISSUE TITLE
Make breadcrumbs available in all themes

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#783]
```[tasklist]
### Tasks
- [x] create figma sheet
- [x] copy tokens in all themes
- [x] finetune tokens for all themes
- [x] Bingel DC
- [x] Bingel INT
- [x] Clickedu
- [x] Editorial Suite
- [x] ItsLearning
- [x] Kampus
- [x] Magister light
- [x] Magister dark
- [x] Max Online
- [x] My digital book
- [x] Myvanin
- [x] NEON light
- [x] NEON dark
- [x] Sanoma Utbilning
- [ ] TEAS
- [ ] publish breadcrumbs in all themes
```
