### ISSUE TITLE
Typography of Avatar

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#813]
See feedback: https://www.figma.com/file/PFwUIMEkE3UNBMtNi7Pnrx/ItsLearning-Light-mode?type=design&node-id=3279%3A7254&mode=design&t=RZkGII5kPSn11dp6-1

https://dna.iddinkgroup.com/?path=/story/avatar--basic&args=size:sm
@storybook/cli - Storybook

[https://dna.iddinkgroup.com/?path=/story/avatar--basic&args=size:](https://dna.iddinkgroup.com/?path=/story/avatar--basic&args=size:sm)xs
@storybook/cli - Storybook
```[tasklist]
### Tasks
- [x] title should be at least 14px
- [x] subtitle should be at least 12px
- [x] update all themes with new typography
- [x] truncate if title or subtitle is too long (3 dots)
- [x] use the tooltip when the title is truncated (desktop)
- [x] don't show truncated subtitle in tooltip
- [x] font-size should be a bit smaller in the SM avatar
```

**Comment by Diaan** [comment]
Do we also want a tooltip when the avatar is imageOnly? Or should it be an additional option?
