### ISSUE TITLE
[Avatar] Title with a Link

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#818]
Make it possible to replace the title with a link. (both figma and code)
Refactor display of the name, so it doesn't use the name object but just slot to render the name (developers can ass the link in the slot)

```[tasklist]
### Tasks
- [x] replace title with link (figma)
- [x] make it possible to add a link instead of a title (code)
- [x] avatar + link are clickable as a whole, they do have the same target
- [x] add a href styling (deliver tokens) use borderRadius.focusring.default for border radius of focus ring
- [x] Documentation: possible to use as a link, but not usable as an action (wrap it in a clickable element) (Alvaro)
```

**Comment by DanielleRameau** [comment]
![Uploading Screenshot 2023-12-13 at 13.00.30.png…]()

**Comment by DanielleRameau** [comment]
![Image](https://github.com/sl-design-system/components/assets/111998351/c0be8f71-6478-4da8-bd9b-67b10d3dc5e6)

**Comment by jpzwarte** [comment]
My suggestion would be to have an `href` property on the avatar, and then have the avatar wrap the display name in a link tag.  This is also how `<sl-tab>` works.
