### ISSUE TITLE
Editorial Suite theme

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#825]
See colors in Figma

```[tasklist]
### Tasks
- [x] Create theme
- [x] avatar
- [x] badge
- [x] buttons
- [x] checkbox
- [x] dialog
- [x] help text
- [x] inline message
- [x] label
- [x] popover
- [x] radio button
- [x] select
- [x] switch
- [x] text area
- [x] text field
- [x] tooltip
```
For now ETSL will use their own colors due to inconsistency reasons. Once they have implemented the SL components in most places they can replace their theme for the SL theme

```[tasklist]
### MyVanin theme fixing
- [x] help text
- [x] disabled button
- [x] changes input.option (see comments)
- [x] consistent disabled states in all components
- [x] fix tooltip background
- [x] switch active success > primary color
```

```[tasklist]
### Kampus
- [x] update dialog
- [x] update popover
- [x] update warning colors in base colors
- [x] update warning button
- [x] update warning inline message
- [x] remove errors in button tokens
```

```[tasklist]
### All themes
- [x] remove focus tokens in color.button
- [x] Sanoma Learning
- [x] bingel DC
- [x] bingel int
- [x] clickedu
- [x] itslearning
- [x] kampus
- [x] max online
- [x] my van in
- [x] neon light
- [x] neon dark
- [x] teas
- [x] editorial suite
```

**Comment by DanielleRameau** [comment]
ETSL designers are reviewing the theme right now. Waiting for their input.
