### ISSUE TITLE
Info badge

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#843]
Info tokens are not defined for the badge component but are an existing variant in the figma component.

```[tasklist]
### Tasks
- [x] add info tokens
- [x] make info badge available in storybook
- [x] Bingel INT
- [x] Bingel DC
- [x] Sanoma Learning
- [x] Clickedu
- [x] ES
- [x] Itslearning
- [x] Kampus
- [x] Magister dark
- [x] Magister light
- [x] Max online
- [x] My digital book
- [x] My vanin
- [x] NEON light
- [x] NEON dark
- [x] Sanoma Utbildning (see branch #922)
- [x] TEAS
- [ ] https://github.com/sl-design-system/components/issues/852
```

**Comment by Diaan** [comment]
While you're working on the tokens for the badge maybe also look at the primary tag in dark mode for SL? Because that doesn't really work very well:
![Image](https://github.com/sl-design-system/components/assets/1351956/ffa518d7-3902-4ef9-a328-a4cc58c6933c)

**Comment by Diaan** [comment]
For Magister and My Vanin the padding/radius tokens appear to be missing: 

![Image](https://github.com/sl-design-system/components/assets/1351956/1f7d20e5-be04-4172-8819-7f4532900b5e)
![Image](https://github.com/sl-design-system/components/assets/1351956/4c9d95c0-33dd-4415-a623-44d33505ee43)
