### ISSUE TITLE
Title in inline message shoudn't be mandatory

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#844]
```[tasklist]
### Tasks
- [x] code: switch default and named slot "description"; default should be "Description" and named slot should be "title"
- [x] figma: add toggle for title (in core)
- [x] update component in figma in all themes
```

**Comment by DanielleRameau** [comment]
![Image](https://github.com/sl-design-system/components/assets/111998351/76f5a8da-4adf-4bb0-87fc-f3009fa78bd1)
