### ISSUE TITLE
List styling in inline message

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#846]
There is the 3rd element, error list, hidden. I don't think that we actually need it:

- [x] This is another style (smaller font-size) to maintain
- [x] Designers can create bullet points or something else that they need in the description text
- [x] The font-size of the error list is very small which might provoke accessibility issues/concerns
- [x] The Figma component is not very flexible: if I need the list before ot in between the description text, I need to detach
```[tasklist]
### Tasks
- [x] Remove list option, let designers create a list on their own in the description box
- [x] Update in all themes
```
