### ISSUE TITLE
button-size in inline-message

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#847]
I believe the button size might be lg: it will still look fine but provide much bigger target area. 
```[tasklist]
### Tasks
- [ ] update in code
- [x] update in figma
- [x] button info tokens are available in this branch
- [ ] double check
```

**Comment by DanielleRameau** [comment]
will be picked up in #851
