### ISSUE TITLE
implement default close button in info inline message instead of primary

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#851]
Quick fix: Use a info **close** button instead of a primary 

![Image](https://github.com/sl-design-system/components/assets/111998351/fe33f713-6729-4ea7-be31-b1f6c0a304e8)
(example in clickedu)

Comment: I think we need to add a set of info buttons for info variants
```[tasklist]
### Tasks
- [x] add info button variant
- [x] add info button to all themes
- [x] update info button in info message (all themes) figma
- [ ] update large info button in info message (code)
- [ ] add info button in storybook as well
```
