### ISSUE TITLE
TEAS feedback

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#854]
**Note:**
_Refine issues together with the team to shape this story_
Some tasks/issues do apply to other themes as well. Convert the task to an issue and link to the feature of the component. Keep theme-specific tasks in this story.

```[tasklist]
### Tasks
- [x] Ghost primary button is sometimes placed on the primary50 background, so the accessible contrast is not met. Could you please increase it minimum to primary500?
- [x] dialog: For TEAS, the most common case for this slot would be the text content for explicit confirmation. With the current solution, I need to create the text, move it, wrap it into a component, and then put it in the slot. Would it be possible to add the text in the component, so I can write directly in it? (Alvaro)
- [x] dialog: Incorrect "danger" button used (is showing buttons from another theme)
- [x] switch: Incorrect font for sm and lg. Should be Open Sans
- [x] tooltip: one o'clock doesn't display correctly (Roald)
- [x] tooltip: 5-12 o'clock has a pointer colored in blue (Roald)
- [x] tooltip: Incorrect font. Should be Open sans
- [x] select: font-size inside component doesn't update (when switching md/lg) (Roald)
- [x] select: labels have incorrect font (should be Open Sans)
- [x] select: chevron color should be base-black, not #222222 (Roald)
- [x] dialog: When the title or subtitle is hidden, the space between the upper part and the slot doesn't change. Not sure if it's intentional - I think it should adapt to the height of the top part. https://www.figma.com/file/Aemc0sVA8V2CDNG706bGQv?node-id=3490:57717&mode=design#656488524 (Alvaro)
- [x] Badge, double selection bug https://www.figma.com/file/Aemc0sVA8V2CDNG706bGQv?node-id=3522:2675&mode=design#657879451 (Roald)
- [x] Badge, icon offset https://www.figma.com/file/Aemc0sVA8V2CDNG706bGQv?node-id=3522:2675&mode=design#657875706 (Roald)
- [x] dialog: focusrring of close button is visible on hover, https://www.figma.com/file/Aemc0sVA8V2CDNG706bGQv?node-id=3490:57717&mode=design#657867097
- [x] Popover: pointer is crashing at 10 o'clock: https://www.figma.com/file/Aemc0sVA8V2CDNG706bGQv?node-id=3396:14083&mode=design#658014221 (Roald)
- [x] popover: disabled state is missing in menu: https://www.figma.com/file/Aemc0sVA8V2CDNG706bGQv?node-id=3396:14121&mode=design#656514599 (Roald)
- [x] Switch: (all in medium state) When disabled the spacing between  label and helper changes. (Alvaro)
- [x] Textarea: when hovering over a label in protytpe, it turns back into "Label" (Roald)
- [x] Textarea: It's hard to resize the width of component. I believe 2 top layers' width is set to fixed. (Roald)
```

```[tasklist]
### Magister
- [x] padding block text field should be 6px instead of 8px (Roald)
```

![Image](https://github.com/sl-design-system/components/assets/111998351/1888a82e-3edb-401e-bb0a-fbd803e17a86)
![Image](https://github.com/sl-design-system/components/assets/111998351/ba4eff81-1ac6-4424-a462-61ae4664d199)

**Comment by DanielleRameau** [comment]
Marcin will deliver more feedback next week

**Comment by marcin-siekaniec** [comment]
Hello, I'm done with the review. All comments are already in Figma :)
