### ISSUE TITLE
Add small checkbox

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#877]
We need a small checkbox for in the grid component the height of the medium checkbox is too big. See example in comments.

```[tasklist]
### Tasks
- [ ] add size sm for checkbox
- [ ] add tokens in all themes
- [ ] update in all themes within Figma (checkbox + radiobutton) make sure we don't create a new component but update it in current component for a good design experience
- [ ] update in code
- [ ] update in documentation
- [ ] click target will be the same as md but with bigger padding and a smaller checkbox
```

**Comment by DanielleRameau** [comment]
We need a small checkbox for in the grid component the height of the medium checkbox is too big.

**Comment by DanielleRameau** [comment]
![CleanShot 2024-01-12 at 09 37 18@2x](https://github.com/sl-design-system/components/assets/111998351/b41cdfe9-b8b7-455e-bd89-f76d1660d3f2)
