### ISSUE TITLE
Translate all strings to the languages of the core products

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#880]
```[tasklist]
### Tasks
- [ ] Find out if there is a translation desk within SL or an external company we can use
- [ ] Create list of people who can translate our copy
- [ ] find out which languages needs to be supported
- [ ] Create a 'translation' page on the documentation website, provide guideline about translations (CFA is repsonsible for translation)
```

**Comment by DanielleRameau** [comment]
Place on 'refining' again after outcome

**Comment by DanielleRameau** [comment]
Is it possible to provide documentation only so the CFA can dot this on their own?
