### ISSUE TITLE
My Digital Book

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#882]
```[tasklist]
### Tasks
- [x] Claudia will deliver colors and fonts (in figma)
- [x] Make copy of My Van In theme
- [x] Add My Digital Book theme (design)
- [x] Add My Digital Book theme (dev)
- [x] Change color
- [x] Test all components
```

**Comment by DanielleRameau** [comment]
CFA is reviewing the theme
