### ISSUE TITLE
Sanoma Utbildning

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#922]
New theme based on myvanin theme, Anna Magiera will deliver new colors.
April
```[tasklist]
### Tasks
- [x] add sanoma utbildning theme
- [x] copy tokens from myvanin theme
- [x] add new primary and accent colors
- [x] avatar
- [x] badge
- [x] button
- [x] card
- [x] checkbox
- [x] dialog
- [x] help text
- [x] inline message
- [x] label
- [x] popover
- [x] radio button
- [x] select
- [x] skeleton
- [x] spinner
- [x] switch
- [x] tabs
- [x] text area
- [x] text field
- [x] tooltip
- [x] update spinner info
```
