### ISSUE TITLE
Visuals for overview page

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#952]
```[tasklist]
### Tasks
- [x] add list of components for visuals
- [x] Avatar
- [x] Visual Badge
- [x] Visual Button
- [x] Visual Card
- [x] Visual Dialog
- [x] Visual Icon
- [x] Visual Inline Message
- [x] Visual Popover
- [x] Visual Radio
- [x] Visual Checkbox
- [x] Visual Select
- [x] Visual Tooltip
- [x] Visual Spinner
- [x] Visual Skeleton
- [x] Visual Switch
- [x] Visual Tabs
- [x] Visual Text Field
- [x] Visual Text Area
- [ ] Visual Accordion
- [ ] Visual Breadcrumbs
- [ ] clean up placeholders
```

**Comment by arecuenco-dsgn** [comment]
All the visual svgs are done except accordion and breadcrumbs because the UI is still in progress.

Here is the SVG of the visuals:
[sl-overvie-visuals.json](https://github.com/sl-design-system/components/files/14297899/sl-overvie-visuals.json)

We are creating new components pages in different branches, here is the list of the SVGs that are done (include) in this branch:
- avatar
- button
- checkbox
- dialog
- popover
- radio-group
- select
- skeleton
- switch
- tab-group
- text-field
- textarea
- tooltip

This are the SVGs that are left:
- Inline Message
- Accordion
- Breadcrumbs
- Spinner
- Badge
- Card

**Comment by arecuenco-dsgn** [comment]
Updated:
- Card  ✅
- Badge  ✅
- Spinner  ✅
- Inline Message  ✅

Pending the cover visuals due to UI is in progress:
- Accordion
- Breadcrumbs
