### ISSUE TITLE
[Contextual Menu] Create UI and design tokens

### ISSUE THREAD

**Issue by DanielleRameau** [sl-design-system/components#981]
```[tasklist]
### Tasks
- [x] Create UI based on existing component
- [x] Design tokens for SL light mode (based on contextual tokens)
- [x] Design tokens for SL dark mode (based on contextual tokens)
- [ ] update theme build for the new tokens (jeroen)
```

**Comment by RoaldBoerema** [comment]
@DanielleRameau The colors for the new Contextual tokens for SL dark need to be looked at. They are now just the inversed order of the light mode, but they could do with some tweaking.

**Comment by RoaldBoerema** [comment]
Components and sheet are ready for copying
